### PR TITLE
Allow registration even if getting push token fails

### PR DESCRIPTION
**Pull request by davidvavra**
Some users are reporting that they can't get through registration due to IOException on getting push token

### CODE REVIEW

**Comment by Kobzol** [comment]
Sending `null` for `pushRegistrationToken` will fail on the current backend, please send an empty string instead.

**Comment by davidvavra** [comment]
@Kobzol I added "error" string, imho better than empty string.

**Comment by Kobzol** [comment]
Ok, it's fine.

**Comment by davidvavra** [comment]
@Kobzol I need approval :)

**Pull request merged**
